name: Generate GitHub Stats (SVG)

on:
  schedule:
    - cron: "0 0 * * 1" # weekly
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create output directory
        run: mkdir -p assets/github

      - name: Download GitHub Stats SVG
        run: |
          curl -L \
            "https://github-readme-stats.vercel.app/api?username=himanshuramavat&show_icons=true&include_all_commits=true&count_private=true&theme=transparent&hide_border=true" \
            -o assets/github/stats.svg

      - name: Download Top Languages SVG
        run: |
          curl -L \
            "https://github-readme-stats.vercel.app/api/top-langs/?username=himanshuramavat&layout=compact&theme=transparent&hide_border=true" \
            -o assets/github/langs.svg

      - name: Commit only if files changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add assets/github/*.svg
          git diff --cached --quiet || git commit -m "chore: update GitHub stats"
          git push
